### ISSUE TITLE
Fix download link in readme

### ISSUE THREAD

**Issue by MatyashDen** [xorum-io/ReKamp#1]
![image](https://user-images.githubusercontent.com/42153507/81167293-a9d27180-8f9d-11ea-9070-1bc72697d500.png)
i think it's should be `maven { url "https://dl.bintray.com/xorum-io/ReKamp" }`?

**Comment by yev-kanivets** [comment]
@MatyashDen you are right. I've not updated ReadMe yet.

**Comment by yev-kanivets** [comment]
Fixed.
